// Generated by CoffeeScript 1.10.0
var app;

app = angular.module('AMPlaygroundApp0', ['ngMaterial', 'ngRoute', 'ngMessages', 'listControllers', 'loginControllers', 'newControllers']);

app.config([
  '$routeProvider', function($routeProvider) {
    return $routeProvider.when('/orders', {
      templateUrl: 'partials/order-list.html',
      controller: 'ListCtrl'
    }).when('/login', {
      templateUrl: 'partials/login.html',
      controller: 'LoginCtrl'
    }).when('/new', {
      templateUrl: 'partials/new-order.html',
      controller: 'NewCtrl'
    }).otherwise({
      redirectTo: '/login'
    });
  }
]);

//# sourceMappingURL=app.js.map
