// Generated by CoffeeScript 1.10.0
angular.module('AMPlaygroundApp0', ['ngMaterial', 'ngRoute', 'ngMessages', 'ngStorage', 'listControllers', 'loginControllers', 'newControllers']).constant('BASE_URL', 'http://192.168.1.233:8233').config([
  '$routeProvider', function($routeProvider) {
    return $routeProvider.when('/orders', {
      templateUrl: 'partials/order-list.html',
      controller: 'ListCtrl'
    }).when('/login', {
      templateUrl: 'partials/login.html',
      controller: 'LoginCtrl'
    }).when('/new', {
      templateUrl: 'partials/new-order.html',
      controller: 'NewCtrl'
    }).otherwise({
      redirectTo: '/login'
    });
  }
]).factory('APIURLProcessor', function($q, $localStorage, BASE_URL) {
  return {
    request: function(config) {
      if (config.url[0] === '/') {
        config.url = BASE_URL + config.url;
        config.headers['Authorization'] = 'Token ' + $localStorage.token;
      }
      return config;
    }
  };
}).config([
  '$httpProvider', function($httpProvider) {
    return $httpProvider.interceptors.push('APIURLProcessor');
  }
]);

//# sourceMappingURL=app.js.map
