// Generated by CoffeeScript 1.10.0
var listControllers;

listControllers = angular.module('listControllers', ['ngMaterial', 'ngMessages', 'ngStorage']);

listControllers.controller('ListCtrl', [
  '$scope', '$http', '$location', '$mdDialog', '$localStorage', function($scope, $http, $location, $mdDialog, $localStorage) {
    var originatorEv;
    $scope.isLoading = true;
    $http({
      method: 'GET',
      url: '/orders'
    }).then(function(response) {
      $scope.isLoading = false;
      return $scope.orders = response.data.orders;
    }, function(response) {
      return $location.path("login");
    });
    originatorEv = null;
    $scope.openMenu = function($mdOpenMenu, ev) {
      originatorEv = ev;
      $mdOpenMenu(ev);
    };
    $scope.showQR = function(ev, token) {
      return $mdDialog.show({
        targetEvent: ev,
        template: '<md-dialog ng-click="hide()">\n    <md-dialog-content>\n        <qr text="\'' + token + '\'"></qr>\n    </md-dialog-content>\n</md-dialog>',
        clickOutsideToClose: true,
        controller: function($scope, $mdDialog) {
          return $scope.hide = function() {
            return $mdDialog.hide();
          };
        }
      });
    };
    $scope.newOrder = function() {
      return $location.path("new");
    };
    return $scope.logout = function() {
      delete $localStorage.token;
      return $location.path("login");
    };
  }
]);

//# sourceMappingURL=listControllers.js.map
