// Generated by CoffeeScript 1.10.0
var loginControllers;

loginControllers = angular.module('loginControllers', ['ngMaterial', 'ngMessages']);

loginControllers.controller('LoginCtrl', [
  '$scope', '$http', '$location', '$rootScope', function($scope, $http, $location, $rootScope) {
    $scope.user = {};
    return $scope.login = function() {
      $location.path("orders");
      return $rootScope.username = $scope.user.username;
    };
  }
]);

//# sourceMappingURL=loginControllers.js.map
