// Generated by CoffeeScript 1.10.0
var loginControllers;

loginControllers = angular.module('loginControllers', ['ngMaterial', 'ngMessages', 'ngStorage']);

loginControllers.controller('LoginCtrl', [
  '$scope', '$http', '$location', '$localStorage', '$mdToast', function($scope, $http, $location, $localStorage, $mdToast) {
    $scope.user = {};
    $scope.loading = false;
    return $scope.login = function() {
      $scope.loading = true;
      return $http({
        method: 'POST',
        url: '/token',
        data: $scope.user
      }).then(function(response) {
        $localStorage.token = response.data.token;
        return $location.path("orders");
      }, function(response) {
        var msg;
        $scope.loading = false;
        msg = response.data.msg;
        return $mdToast.show($mdToast.simple().textContent(msg));
      });
    };
  }
]);

//# sourceMappingURL=loginControllers.js.map
