// Generated by CoffeeScript 1.10.0
var newControllers;

newControllers = angular.module('newControllers', ['ngMaterial', 'ngMessages']);

newControllers.controller('NewCtrl', [
  '$scope', '$http', '$location', '$mdToast', function($scope, $http, $location, $mdToast) {
    $scope.order = {};
    $scope.door = {};
    $scope.has_door = false;
    $scope.back = function() {
      return $location.path('orders');
    };
    $scope.avail = '13:00';
    return $scope.postOrder = function() {
      $scope.back();
      return $mdToast.show($mdToast.simple().textContent('You order has been placed!'));
    };
  }
]);

//# sourceMappingURL=newControllers.js.map
